### ISSUE TITLE
AADSTS65001: The user or administrator has not consented to use the application with ID

### ISSUE THREAD

**Issue by malay2012** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof#9]
Hi,

I have created 
A. web application and 
B. Web Api application
C. External Api Application hosted in CloudApp

I have created Azure Ad application given following access -

1. Added WebApi application in App permission list for Web Application(A)
2. Added External application in App permission list for Web Api Application(B)

When I am trying to access the external api(C) from Web Api application(B), I am getting consent issue  WebApi(B). I have used the same steps mentioned in this blog to provide access to the different application.

Code block:
using  method:  authContext.AcquireTokenAsync(resourceId, clientCred, userAssertion)

Thanks,
Malay

**Comment by raldaba** [comment]
I've had this issue in my apps before. This is due to a consent you already gave with an X number of resources. If you go to the management portal where you can revoke consent, do so and try again. This will "re-consent" and this error should go away.

(For my particular case, I hit the consent URL and re-consent again without having to go to my azure profile and revoke consent)

The Azure v2.0 endpoint fixes this issue with dynamic consent. Vittorio explains more here -> https://docs.microsoft.com/en-us/azure/active-directory/active-directory-v2-compare#incremental-and-dynamic-consent

Hope that's helpful.

**Comment by danieldobalian** [comment]
@malay2012 You can also try hitting the "Grant Permissions" button in the Azure portal in the delegated permissions blade for the app giving you problems.

**Comment by GordonLam** [comment]
There is a case when your Web Application (A) and Web Api Application(B), are in different AAD tenant, then you must re-consent.
